### PR TITLE
Update headers to support RN >= 0.40

### PR DESCRIPTION
**Pull request by varungupta85**

### CODE REVIEW

**Comment by mobinni** [comment]
Please merge this

**Review by mobinni — APPROVED** [review]

**Comment by guns2410** [comment]
Please merge this ASAP please

**Comment by tallmorgan** [comment]
I can confirm that `yarn add holmesal/react-native-ios-notification-actions#17/head` is compatible with `react-native` version `0.44.0`. Great PR.

**Comment by holmesal** [comment]
Thanks! Sorry for the delay, I'm not actively maintaining this repo and will add a notice to the README

**Pull request merged**
